#ifndef PS_KEYDEFINES_INCLUDED
#define PS_KEYDEFINES_INCLUDED

#define ALPHA_BLEND defined(_ALPHABLEND_ON)

#define ALPHA_PREMULTIPLY defined(_ALPHAPREMULTIPLY_ON)

#define ALPHA_ADD defined(_COLORCOLOR_ON)

#define ALPHA_ADD_SOFT defined(_SPECGLOSSMAP)

#define ALPHA_MULTIPLY defined(_METALLICGLOSSMAP)

#define ALPHA_MULTIPLYX2 defined(_PARALLAXMAP)

#define ALPHA_TEST_ENABLED defined(_ALPHATEST_ON)

#define FILTERING_ENABLED defined(_COLOROVERLAY_ON)

#define DISTORTION_ENABLED defined(EFFECT_BUMP)

#define DISTORTION_UV_ENABLED defined(_NORMALMAP)

#define LAYERED_TEX_ENABLED defined(_DETAIL_MULX2)

#define PULSE_ENABLED defined(_ALPHAMODULATE_ON)

#define FALLOFF_ENABLED defined(DEPTH_OF_FIELD)

#define FLIPBOOK_BLEND_ENABLED defined(_REQUIRE_UV2)

#define FADING_ENABLED defined(_FADING_ON)

#endif // PS_KEYDEFINES_INCLUDED