#ifndef PS_KEYDEFINES_INCLUDED
#define PS_KEYDEFINES_INCLUDED

#define ALPHA_BLEND defined(_ALPHABLEND_ON)

#define ALPHA_PREMULTIPLY defined(_ALPHAPREMULTIPLY_ON)

#define ALPHA_ADD defined(_ALPHA_ADD_ON)

#define ALPHA_ADD_SOFT defined(_ALPHA_ADD_SOFT_ON)

#define ALPHA_MULTIPLY defined(_ALPHA_MUL_ON)

#define ALPHA_MULTIPLYX2 defined(_ALPHA_MULX2_ON)

#define ALPHA_TEST_ENABLED defined(_ALPHATEST_ON)

#define FILTERING_ENABLED defined(_FILTERING_ON)

#define DISTORTION_ENABLED defined(_DISTORTION_ON)

#define DISTORTION_UV_ENABLED defined(_DISTORTION_UV_ON)

#define LAYERED_TEX_ENABLED defined(_LAYERED_TEX_ON)

#define PULSE_ENABLED defined(_PULSE_ON)

#define FALLOFF_ENABLED defined(_FALLOFF_ON)

#define FLIPBOOK_BLEND_ENABLED defined(_FLIPBOOK_BLENDING_ON)

#define FADING_ENABLED defined(_FADING_ON)

#define AUDIOLINK_ENABLED defined(_AUDIOLINK_ON)

#endif // PS_KEYDEFINES_INCLUDED