#ifndef US_KEYWORD_DEFINES
#define US_KEYWORD_DEFINES

#define X_FEATURES defined(UBERX)

#define FORWARD_PASS defined(UNITY_PASS_FORWARDBASE)

#define ADDITIVE_PASS defined(UNITY_PASS_FORWARDADD)

#define SHADOW_PASS defined(UNITY_PASS_SHADOWCASTER)

#define OUTLINE_PASS defined(OUTLINE)

#define VERTEX_LIGHT defined(VERTEXLIGHT_ON)

#define ALPHA_TEST defined(_ALPHATEST_ON)

#define ALPHA_BLEND defined(_ALPHABLEND_ON)

#define ALPHA_PREMULTIPLY defined(_ALPHAPREMULTIPLY_ON)

#define NON_OPAQUE_RENDERING defined(_ALPHATEST_ON) || defined(_ALPHABLEND_ON) || defined(_ALPHAPREMULTIPLY_ON)

#define TRANSPARENT_RENDERING defined(_ALPHABLEND_ON) || defined(_ALPHAPREMULTIPLY_ON)

#define SHADING_ENABLED !defined(_SUNDISK_NONE)

#define PACKED_WORKFLOW defined(_METALLICGLOSSMAP)

#define PACKED_WORKFLOW_BAKED defined(FXAA)

#define SPECULAR_WORKFLOW defined(_SPECGLOSSMAP)

#define DEFAULT_WORKFLOW !defined(_METALLICGLOSSMAP) && !defined(_SPECGLOSSMAP)

#define REFLECTIONS_ENABLED !defined(_GLOSSYREFLECTIONS_OFF)

#define SSR_ENABLED defined(CHROMATIC_ABBERATION_LOW)

#define CUBEMAP_REFLECTIONS defined(_SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A)

#define SPECULAR_ENABLED !defined(_SPECULARHIGHLIGHTS_OFF)

#define ANISO_SPECULAR defined(_SUNDISK_SIMPLE)

#define COMBINED_SPECULAR defined(_SUNDISK_HIGH_QUALITY)

#define GGX_SPECULAR !defined(_SUNDISK_SIMPLE) && !defined(_SUNDISK_HIGH_QUALITY)

#define NORMALMAP_ENABLED defined(_NORMALMAP)

#define DETAIL_NORMALMAP_ENABLED defined(_DETAIL_MULX2)

#define EMISSION_ENABLED defined(_EMISSION)

#define PULSE_ENABLED defined(BLOOM_LENS_DIRT)

#define PARALLAX_ENABLED defined(_PARALLAXMAP)

#define FILTERING_ENABLED defined(_COLORCOLOR_ON)

#define POST_FILTERING_ENABLED defined(_COLOROVERLAY_ON)

#define PBR_PREVIEW_ENABLED defined(USER_LUT)

#define SEPARATE_MASKING defined(_COLORADDSUBDIFF_ON)

#define PACKED_MASKING defined(_REQUIRE_UV2)

#define UV_DISTORTION_ENABLED defined(EFFECT_BUMP)

#define UV_DISTORTION_NORMALMAP defined(GRAIN)

#define DISSOLVE_TEXTURE !defined(_ALPHAMODULATE_ON)

#define DISSOLVE_GEOMETRY defined(DEPTH_OF_FIELD)

#define CUBEMAP_ENABLED defined(_MAPPING_6_FRAMES_LAYOUT)

#define COMBINED_CUBEMAP_ENABLED defined(_TERRAIN_NORMAL_MAP)

#define MATCAP_ENABLED defined(_FADING_ON)

#define ENVIRONMENT_RIM_ENABLED defined(PIXELSNAP_ON)

#define SPRITESHEETS_ENABLED defined(EFFECT_HUE_VARIATION)

#define CLONES_ENABLED defined(BLOOM)

#define REFRACTION_ENABLED defined(DISTORT)

#define REFRACTION_CA_ENABLED defined(CHROMATIC_ABBERATION)

#define VERTEX_MANIP_ENABLED defined(GEOM_TYPE_MESH)

#define MASK_SOS_ENABLED defined(GEOM_TYPE_BRANCH)

#define REFLCUBE_EXISTS defined(VIGNETTE_MASKED)

#define BCDISSOLVE_ENABLED defined(DITHERING)

#endif