#ifndef MOCHIE_STANDARD_KEYDEFINES_INCLUDED
#define MOCHIE_STANDARD_KEYDEFINES_INCLUDED

#define STOCHASTIC_ENABLED defined(_STOCHASTIC_ON)

#define TSS_ENABLED defined(_TSS_ON)

#define TRIPLANAR_ENABLED defined(_TRIPLANAR_ON)

#define DETAIL_STOCHASTIC_ENABLED defined(_DETAIL_STOCHASTIC_ON)

#define DETAIL_TSS_ENABLED defined(_DETAIL_TSS_ON)

#define DETAIL_TRIPLANAR_ENABLED defined(_DETAIL_TRIPLANAR_ON)

#define SSR_ENABLED defined(_SCREENSPACE_REFLECTIONS_ON)

#define WORKFLOW_PACKED defined(_WORKFLOW_PACKED_ON)

#define DETAIL_WORKFLOW_PACKED defined(_DETAIL_WORKFLOW_PACKED_ON)

#define DETAIL_BASECOLOR defined (_DETAIL_MULX2)

#define DETAIL_AO defined(_DETAIL_AO_ON)

#define DETAIL_ROUGH defined(_DETAIL_ROUGH_ON)

#define DETAIL_METALLIC defined(_DETAIL_METALLIC_ON)

#define AUDIOLINK_ENABLED defined(_AUDIOLINK_ON)

#define DETAIL_SAMPLEMODE_ENABLED defined(_DETAIL_SAMPLEMODE_ON)

#define AREALIT_ENABLED defined(_AREALIT_ON)

#define MIRROR_ENABLED defined(_MIRROR_ON)

#endif // MOCHIE_STANDARD_KEYDEFINES_INCLUDED