#ifndef MOCHIE_STANDARD_KEYDEFINES_INCLUDED
#define MOCHIE_STANDARD_KEYDEFINES_INCLUDED

#define STOCHASTIC_ENABLED defined(_STOCHASTIC_ON)

#define TSS_ENABLED defined(_TSS_ON)

#define TRIPLANAR_ENABLED defined(_TRIPLANAR_ON)

#define DECAL_ENABLED defined(_DECAL_ON)

#define REFLECTION_FALLBACK defined(_REFLECTION_FALLBACK_ON)

#define REFLECTION_OVERRIDE defined(_REFLECTION_OVERRIDE_ON)

#define SSR_ENABLED defined(_SCREENSPACE_REFLECTIONS_ON)

#define WORKFLOW_PACKED defined(_WORKFLOW_PACKED_ON)

#define DETAIL_BASECOLOR defined (_DETAIL_MULX2)

#define DETAIL_AO defined(_DETAIL_AO_ON)

#define DETAIL_ROUGH defined(_DETAIL_ROUGH_ON)

#define SUBSURFACE_ENABLED defined(_SUBSURFACE_ON)

#define AUDIOLINK_ENABLED defined(_AUDIOLINK_ON)

#define DETAIL_SAMPLEMODE_ENABLED defined(_DETAIL_SAMPLEMODE_ON)

#endif // MOCHIE_STANDARD_KEYDEFINES_INCLUDED